### ISSUE TITLE
Requires Xcode to be already installed to work

### ISSUE THREAD

**Issue by dgilbert-foreflight** [RobotsAndPencils/homebrew-made#3]
Currently, if you were to run `brew install robotsandpencils/made/xcodes` on a machine which doesn't already have Xcode installed it will fail stating `xcrun: error: unable to find utility "xctest", not a developer tool or in PATH`.

For context, this was when attempting to install on a new M1 Mini.

Given that I see you have the binary at https://github.com/RobotsAndPencils/xcodes/releases/download/0.20.0/xcodes.zip is it possible to NOT compile the code (i.e. `swift run`) and instead update the formula to download and install this to bin?

**Comment by AndrewSB** [comment]
yeah, having Xcode installed already defeats the point of installing Xcode imo

**Comment by AndrewSB** [comment]
dupe of https://github.com/RobotsAndPencils/xcodes/issues/148

**Comment by dgilbert-foreflight** [comment]
https://github.com/RobotsAndPencils/xcodes/issues/148 - fixed
